---
- name: Create VMs from cloned templates
  hosts: all
  become: true
  gather_facts: false

  vars:
    vm_names: "dev-vm01"
    template_name: "ubuntu-22.04-template"
    vm_user: "admin"              # From survey
    vm_password: "SecurePass123"  # From survey
    memory: 2048
    cores: 2
    disk_size: "15G"
    software_to_install: []                # Set via AWX Survey

  tasks:
    - name: Get current list of VMs
      command: qm list
      register: qm_list

    - name: Create VMs by cloning the template
      include_tasks: clone_vm.yml
      loop: "{{ vm_names }}"
      loop_control:
        loop_var: vm_name
