---
- name: Create Cloud-Init Templates on Proxmox
  hosts: all
  gather_facts: false
  become: true

  vars:
    iso_dir: "/var/lib/vz/template/iso"
    storage: "local-lvm"                   # Set from AWX Survey
    bridge: "vmbr0"                         # Set from AWX Survey
    memory: 2048                            # Optional via AWX
    cores: 2                                # Optional via AWX
    disk_size: "10G"                        # Optional via AWX
    vm_user: "admin"
    vm_password: "SecurePass123"
#    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCWhvTm4pj0iNPZyU07C7PhPYRrhDPo6i13whDjGMetSP/Ai5+5J7pfmhA0MtLZnex0uw1SuoIEpG3XDudGD9MHwOSvNp3WMY1VUap2PLQoH+CO8JydZNRoE/yg3zMPP9+dWXIO298kwOyPWooeTkZUVEHbZvT7jA2f6AQmbI+9Fhz7zPmzakbbIQQaSN+43UT4p4cVsFF6QR8WyCh0Psaz2KZt4MXFabU5WwSUtMQD9p+Hv38DlPalM6L6snUuJgq/TsNlU3ELkTUeo/qBsuy7vRO72LpWYg7QfHAuy2AnvH+1KtdTMEJYSEU9DDZUBgDp2bKhH6ivWebp2CZighy/ user@example"

    # OS image lookup table
    os_image_lookup:
      ubuntu-22.04:
        name: "ubuntu-22.04-template"
        url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
      debian-12:
        name: "debian-12-template"
        url: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2"
      centos-9:
        name: "centos-9-template"
        url: "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2"

  tasks:
    - name: Ensure ISO directory exists
      ansible.builtin.file:
        path: "{{ iso_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Get current list of VMs
      command: qm list
      register: qm_list

    - name: Loop through OS types to create templates
      include_tasks: create_template_block.yml
      loop: "{{ os_types }}"
      loop_control:
        loop_var: os_type
