---
- name: Install OpenSCAP and run STIG profile scan
  hosts: all
  become: yes
  vars:
    scap_url: "https://github.com/ComplianceAsCode/content/releases/download/v0.1.76/scap-security-guide-0.1.76.zip"
    scap_zip: "/tmp/scap-security-guide.zip"
    scap_extract_dir: "/opt/scap-security-guide"
    scap_data_file: "{{ scap_extract_dir }}/ssg-ubuntu2004-ds-1.2.xml"
    report_dir: "/var/oscap-reports"
    report_file: "{{ report_dir }}/stig-report.html"

  tasks:

    - name: Install required packages
      apt:
        name:
          - libopenscap8
          - unzip
          - wget
        update_cache: yes
        state: present

    - name: Create directory to extract SCAP content
      file:
        path: "{{ scap_extract_dir }}"
        state: directory
        mode: '0755'

    - name: Download SCAP Security Guide
      get_url:
        url: "{{ scap_url }}"
        dest: "{{ scap_zip }}"
        mode: '0644'

    - name: Unzip SCAP Security Guide
      unarchive:
        src: "{{ scap_zip }}"
        dest: "{{ scap_extract_dir }}"
        remote_src: yes
        extra_opts: [ "-o" ]

    - name: Create report directory
      file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'

    - name: Run OpenSCAP STIG scan
      command: >
        oscap xccdf eval
        --profile xccdf_org.ssgproject.content_profile_stig
        --report {{ report_file }}
        {{ scap_data_file }}
      args:
        warn: false

    - name: Show report path
      debug:
        msg: "✅ STIG scan complete. HTML report saved at: {{ report_file }}"
