---
- name: Install OpenSCAP and run STIG scan
  hosts: all
  become: yes
  vars:
    scap_url: "https://github.com/ComplianceAsCode/content/releases/download/v0.1.76/scap-security-guide-0.1.76.zip"
    scap_dest_dir: "/opt/scap-security-guide"
    scap_zip_file: "{{ scap_dest_dir }}/scap-security-guide-0.1.76.zip"
    scap_data_file: "{{ scap_dest_dir }}/scap-security-guide-0.1.76/ssg-ubuntu2204-ds.xml"
    report_file: "{{ scap_dest_dir }}/stig-report-{{ ansible_date_time.iso8601_basic_short }}.html"

  tasks:

    - name: Install required packages
      apt:
        name:
          - libopenscap8
          - unzip
        state: present
        update_cache: yes

    - name: Create directory for SCAP content
      file:
        path: "{{ scap_dest_dir }}"
        state: directory
        mode: '0755'

    - name: Download SCAP Security Guide
      get_url:
        url: "{{ scap_url }}"
        dest: "{{ scap_zip_file }}"
        mode: '0644'

    - name: Unzip SCAP content
      unarchive:
        src: "{{ scap_zip_file }}"
        dest: "{{ scap_dest_dir }}"
        remote_src: yes

    - name: Run OpenSCAP STIG scan
      command: >
        oscap xccdf eval
        --profile xccdf_org.ssgproject.content_profile_standard
        --report {{ report_file }}
        {{ scap_data_file }}
      register: scap_result
      failed_when: >
        scap_result.rc != 0 and
        ('Obtrusive data from probe!' not in scap_result.stderr)
